Testing
YunoHost-Apps/emailpoubelle_ynh pull request #18
Opened 2021-06-24 13:20 UTC by oufmilo

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2021-06-24 13:20 UTC, oufmilo commented
!testme

2021-06-25 07:04 UTC, oufmilo commented
testme

2021-06-25 07:05 UTC, oufmilo commented
!testme

2021-06-25 13:13 UTC, ericgaspar requested changes

2021-06-25 13:13 UTC, ericgaspar commented on scripts/_common.sh
> +extra_php_dependencies="php7.3-geoip php7.3-cli"
```suggestion
extra_php_dependencies="php${YNH_PHP_VERSION}-geoip php${YNH_PHP_VERSION}-cli"
```

2021-06-25 13:13 UTC, ericgaspar commented on scripts/backup
> +ynh_print_info --message="Backing up the main app directory..."
```suggestion

```

2021-06-25 13:13 UTC, ericgaspar commented on scripts/backup
> +ynh_print_info --message="Backing up nginx web server configuration..."
```suggestion

```

2021-06-25 13:13 UTC, ericgaspar commented on scripts/backup
> +ynh_print_info --message="Backing up cron configuration..."
```suggestion

```

2021-06-25 13:13 UTC, ericgaspar commented on scripts/backup
> +ynh_print_info --message="Backing up postfix conf configuration..."
```suggestion

```

2021-06-25 13:13 UTC, ericgaspar commented on scripts/install
>  service php* reload
```suggestion

```

2021-06-25 13:13 UTC, ericgaspar commented on scripts/upgrade
> +#fi
```suggestion

```

2021-06-25 14:56 UTC, ericgaspar reviewed
I am not sure that the package is called with PHP7.3 version...
cf. https://packages.debian.org/fr/buster/php-geoip

2021-06-25 14:56 UTC, ericgaspar commented on scripts/_common.sh
> +extra_php_dependencies="php${YNH_PHP_VERSION}-geoip php${YNH_PHP_VERSION}-cli"
```suggestion
extra_php_dependencies="php-geoip php${YNH_PHP_VERSION}-cli"
```

2021-06-25 16:34 UTC, ericgaspar commented
!testme

2022-05-25 10:27 UTC, ericgaspar commented
!testme

2022-05-25 13:12 UTC, merged